# Ma Config Laptop
source = ~/.config/hypr/base.conf

# Reglage ecran specifique
monitor=eDP-1,1920x1200@60,0x0,1.25

input {

    touchpad {
        natural_scroll = true  # <--- Change 'false' en 'true'
    }
}
