format = """trkBytes [$directory]($style)$character"""


[directory]

style = "fg:#cba6f7 bold" # A vibrant purple

truncation_length = 0

truncate_to_repo = false

format = "[$path]($style) "

home_symbol = "~"

truncation_symbol = "…/"


[character]

success_symbol = "[❯](fg:#f5c2e7)" # A vibrant pink

error_symbol = "[>](bold green)"  # Same as success so it's not confusing

[hostname]
disabled = true

[username]
disabled = true
